### ISSUE TITLE
已经使用，期待更新~

### ISSUE THREAD

**Issue by poyo96** [sve1r/OMEN-By-HP-15-ax225TX-Hackintosh-EFI#1]
大佬电脑上会出现睡眠秒醒的情况吗？

**Comment by sve1r** [comment]
有时会有时候不会，不过我都习惯直接关机了....

**Comment by poyo96** [comment]
> 有时会有时候不会，不过我都习惯直接关机了....

我加了一个GPRW.aml不会秒醒啦

就是偶尔睡一下午，他自己还会唤醒

然后我把电能小憩也给关了，把待机联网也给关了
再看看效果吧。

**Comment by sve1r** [comment]
好的我已经发现了。
插着电就不能合盖睡眠  
不连接电源啥都正常

**Comment by poyo96** [comment]
加了gprw好了很多，不过oc引导打不开win了，所以双系统切换，我都是直接在BIOS里用F9调整的
