### ISSUE TITLE
IntelFirmware: can not proceed response

### ISSUE THREAD

**Issue by nulldx** [sve1r/OMEN-By-HP-15-ax225TX-Hackintosh-EFI#10]
`IntelFirmware: HCI_OP_INTEL_VERSION
IntelFirmware：interrupt wait
IntelFirmware: Found device firmware ibt-hw-37.8.18-fw-1,10.3.11.e.hseq」
IntelFirmware: request firmware successIntelFirmware: interrupt continue
IntelFirmware: HCI_OP_INTEL_ENTER_MFG
IntelFiriware： interrupt wait
IntelFirmware: interrupt continue
IntelFirmware: can not proceed response 
IntelFirmware: can not proceed response 
IntelFirmware: interrupt continue 
IntelFirmware：HCI_OP_INTEL_EXIT_MFG
IntelFirmware: interrupt wait
IntelFirmware: interrupt continue 
IntelFirmware：HCI_OP_INTEL_EVENT_MRSK
IntelFirmware: interrupt wait
IntelFirmware: can not proceed response
IntelFirmware: interrupt continue 
IntelFirmware: End download
IntelFirmware: Clean up...`
谷歌了大概是蓝牙的问题？但是没有找到解决方法，麻烦大佬看一下有没有解决方法
用的是0.71的EFI,电脑是原厂的硬件换了一个SAMSUNG MZVLW256HEHP-000L2的SSD

**Comment by nulldx** [comment]
IntelFirmware: HCI_OP_INTEL_VERSION
IntelFirmware：interrupt wait
IntelFirmware: Found device firmware ibt-hw-37.8.18-fw-1,10.3.11.e.hseq」
IntelFirmware: request firmware successIntelFirmware: interrupt continue
IntelFirmware: HCI_OP_INTEL_ENTER_MFG
IntelFiriware： interrupt wait
IntelFirmware: interrupt continue
IntelFirmware: can not proceed response 
IntelFirmware: can not proceed response 
IntelFirmware: interrupt continue 
IntelFirmware：HCI_OP_INTEL_EXIT_MFG
IntelFirmware: interrupt wait
IntelFirmware: interrupt continue 
IntelFirmware：HCI_OP_INTEL_EVENT_MRSK
IntelFirmware: interrupt wait
IntelFirmware: can not proceed response
IntelFirmware: interrupt continue 
IntelFirmware: End download
IntelFirmware: Clean up...

**Comment by sve1r** [comment]
首先 你可以退回 0.7.0 版本试试看有没有这个错误。
如果没有的话可能是intel蓝牙驱动的问题 等下个版本修复就好了

**Comment by nulldx** [comment]
> 首先 你可以退回 0.7.0 版本试试看有没有这个错误。
> 如果没有的话可能是intel蓝牙驱动的问题 等下个版本修复就好了

0.7是一样的报错，无奈

**Comment by nulldx** [comment]
> > 首先你可以恢复0.7.0版本破解看看有没有这个错误。
> > 如果没有的话可能是intel蓝牙驱动的问题等下个版本就好了
> 
> 0.7是一样的报错，无奈

**Comment by nulldx** [comment]
> > 首先你可以恢复0.7.0版本破解看看有没有这个错误。
> > 如果没有的话可能是intel蓝牙驱动的问题等下个版本就好了
> 
> 0.7是一样的报错，无奈

我在https://github.com/OpenIntelWireless的issue里面看到和我差不多的问题。如果我不需要蓝牙，我能不能跳过检查蓝牙来启动安装macos？

**Comment by sve1r** [comment]
可以的 ，把配置文件中的强制加载蓝牙驱动删掉就好了

**Comment by nulldx** [comment]
> 可以的 ，把配置文件中的强制加载蓝牙驱动删掉就好了

感谢分享efi，已经装上mac了。蓝牙wifi均可用。
