### ISSUE TITLE
黑苹果各功能完美实现

### ISSUE THREAD

**Issue by MooNahiY** [sve1r/OMEN-By-HP-15-ax225TX-Hackintosh-EFI#11]
谢谢大佬提供的EFI，使用之后黑苹果各功能完美实现=。=
有一点就是，在使用过程中发现键盘右侧那部分会很热，不知道是什么原因。
emmm好像又没有那么的热，现在用着大概是温热的程度。
用旧电脑体验了一下macOS之后好想弄一个mini主机安装黑苹果哈哈

**Comment by sve1r** [comment]
键盘右侧到数字小键盘区域下面有CPU和显卡，平常使用温温热是正常的
