### ISSUE TITLE
引导10.14.6会卡住

### ISSUE THREAD

**Issue by sjzybl** [sve1r/OMEN-By-HP-15-ax225TX-Hackintosh-EFI#12]
您好，我用您这个配置文件引导我安装的10.14.6系统，代码会停在intelfirmware: virtual viod usbdevicecontroller::free()这样一行代码上，然后卡几秒钟之后，屏幕会跳出来一个类似于禁止通行交通标示的一个○里面一道斜杠的标志，另外我还用您这个efi引导试图安装11.5.2，但是也会出现类似的情况，请问您知道这是怎么回事么。

**Comment by sve1r** [comment]
请先确认是否处理器以及主板型号是否和我的相同 

如果可以 麻烦把配置详细信息贴一下

**Comment by sjzybl** [comment]
我也是暗影精灵2 pro，颜色可能和楼主不一样，我就是暗影精灵黑红那个配色的，但是惠普支持中心查到的型号和您的相同，OMEN by HP 15-ax255tx 。

然后笔记本电脑主板bios也升级到和您一样的版本了，
固态我是自己后换的海康威视 c2000pro，
和您的配置另一个不一样的地方是无线网卡我是后换的ax200。

我今天试了试用您的配置把acpi里面的内容换成以前用的一个clover的acpi，就能正常进入10.14.6了，不过还是无法安装新的11.5.2.

**Comment by sve1r** [comment]
处理器是不是 i7 的

**Comment by sve1r** [comment]
确认是不是使用了镜像的配置 而非本地的efi

**Comment by sve1r** [comment]
最好再上传一下 -v 参数的日志

**Comment by sjzybl** [comment]
处理器也是i5-7300hq这个，应该是除了网卡配置都一样，efi没选错，我本地的是clover引导的，然后oc拷贝到硬盘里了，-v的日志我查查怎么拷贝出来，拷贝出来之后发给您。

**Comment by sjzybl** [comment]
那个。。我查了查没查到怎么找-v的日志。。然后用occ的boot.log抓取不出来，说没有日志。。。所以。。求问我能在哪找-v参数的日志

**Comment by sve1r** [comment]
occ 启动的时候 手动输入 -v 就好

**Comment by sjzybl** [comment]
> occ 启动的时候 手动输入 -v 就好

就是。。我先用clover进macos，然后启动occ，在启动的时候按一下-v ？

**Comment by sjzybl** [comment]
实在抱歉。。我还是没能找到在哪能拷贝出来日志，这是卡代码的那一个屏幕的照片以及卡完代码之后出现的屏幕的照片，您看看是否可以。
http://gofile.me/6SzE8/tTCq8CBVr
http://gofile.me/6SzE8/mw98nOQ3q

**Comment by sve1r** [comment]
Clover 不支持本项目内使用的 IntelWiFi 驱动 

你可以使用包含了通用配置的 OpenCore 安装镜像进行安装 
安装完成后再替换成项目内的 EFI

**Comment by sjzybl** [comment]
> Clover 不支持本项目内使用的 IntelWiFi 驱动
> 
> 你可以使用包含了通用配置的 OpenCore 安装镜像进行安装
> 安装完成后再替换成项目内的 EFI

emm。。我是已经安装好10.14了，然后用您这个efi启动不了。。。-v的话卡的代码就是上面那两个图片。。但是如果我把我那个clover引导中的acpi部分替换到您的这个oc配置中，就可以了。。
但是讲道理我和您的配置除了网卡和固态应该都一样。。而且网卡用的驱动也一样。。所以不太懂为啥不能直接用您这个efi。。毕竟自己不懂这个，自己瞎动过的。。感觉用起来还是怕出问题。

**Comment by sve1r** [comment]
显卡配置不正确

**Comment by sjzybl** [comment]
哦哦。。那麻烦问下。。如果我不想改整个acpi的话。我应该改什么地方呢。还是我需要给显卡驱动升个级啥的？
我的显卡在win里显示也是630.但是不知道为什么在hacktintool里显示的就是620.
然后我用您的配置如果只更改device properties这部分，也还是不能正常启动

**Comment by sve1r** [comment]
说明你的 EFI 的显卡缓冲帧配置不正确
你可以参考或者搜索别人的Clover配置进行修改

**Comment by sjzybl** [comment]
> 说明你的 EFI 的显卡缓冲帧配置不正确
> 你可以参考或者搜索别人的Clover配置进行修改

那个。。我有点懵。。显卡缓冲帧补丁不是device properties这部分的内容么，我是改acpi这部分的内容。。就能用了。。这是为啥。。。
