### ISSUE TITLE
设置-网络-蓝牙-找不到pan设备

### ISSUE THREAD

**Issue by Adek2012** [sve1r/OMEN-By-HP-15-ax225TX-Hackintosh-EFI#13]
在设置-网络-蓝牙-找不到pan设备，设置-蓝牙中可以使用蓝牙，也可以连接蓝牙设备，连接AirPods Pro听歌时断断续续，不知道是什么原因

**Comment by sve1r** [comment]
这个是 Intel 蓝牙固件的问题.
当 Intel 无线网卡正在正常连接 WiFi 使用时就会有一定的几率出现这个状况.
目前暂无合适的解决方法
