### ISSUE TITLE
无法引导

### ISSUE THREAD

**Issue by kimoefox** [sve1r/OMEN-By-HP-15-ax225TX-Hackintosh-EFI#14]
发现个尴尬的事情，usb3.0没法引导，得插到2.0引导安装盘
安装盘可以完成安装，但是没法进系统。。
这就尴尬了，卡进度条了

**Comment by kimoefox** [comment]
没事了我是傻逼
我居然用了OpenCpre.efi进行引导，建议把我挂出来防止有小白2333333333333

**Comment by sve1r** [comment]
............
