### ISSUE TITLE
一个建议，一个反馈

### ISSUE THREAD

**Issue by kimoefox** [sve1r/OMEN-By-HP-15-ax225TX-Hackintosh-EFI#15]
先吹一波，大佬的efi已经趋近完美了，网卡虽说只有65Mbps当时足够用了，隔空投送我帮大佬测试了，我这台机是不行的
然后建议
我这台是i7的版本，可能因为这个吧，我在u3的口插u3的u盘并不能识别，就一点反应都没有，插u2的盘就可以
然后基于Xstar大佬的efi里面的Kext我重新搞了一下USBPort.kext
[USBPort.zip](https://github.com/sve1r/OMEN-By-HP-15-ax225TX-Hackintosh-EFI/files/7319850/USBPort.zip)

第二个就是触摸板
触摸板的话目前貌似只能滑动和随机触发左键右键，真的就是看心情，目前我没成功过使用2指手势或者3指手势
（主要是不会“借鉴”Xtar大佬的PS2自编译（雾））

最后如果大大看到了，希望能搞搞触摸板，谢谢大佬了

比心❤️～

**Comment by sve1r** [comment]
i7 版本 USB 的问题 
可以根据个人的实际需要使用 Hackintool 中的 USB 工具自己定制设备的 USB端口
然后直接替换 EFI 中的 ACPI 即可（替换前请注意备份）

---
触摸板的问题
我亲自实测 目前触摸板支持
- 双指捏合缩放
- 双指上下滑滚动
- 双指右边缘左滑展开通知中心
- 三指上下滑展开调度中心
- 捏拢拇指及其他三指打开 启动台
- 张开拇指及其他三指 显示桌面（这个比较难出现，但还是可以使用）

为测试通过的仅有
- 双指在页面间移动 （会识别为前往上一页）
- 三指左右轻扫（无法识别横向手势）

**Comment by kimoefox** [comment]
i7 版本 USB 的问题
如果用原来的efi文件里面的injecct all 貌似没有识别到有u3的口
anyway 现在解决了23333

---------
触摸板的话现在是这样，手势倒是可以用，就是点按（一根手指）会bug，迷惑行为2333333333
哦对还有就是系统设置里面木有识别到有触摸板（塔器派德2333333）

**Comment by Sword6988** [comment]
> 先吹一波，大佬的efi已经接近这完美了，网卡虽然说只有65Mbps的当时英国用了，隔空投送我帮大佬测试了，我台机是不行的 然后建议 我台是i7的版本，可能是因为这个吧，我在u3的口插u3的u盘并不能识别，就一点反应都没有，插u2的盘就可以 然后基于Xstar大佬的efi里面的kext我搞了一下USBPort.kext [USB端口.zip](https://github.com/sve1r/OMEN-By-HP-15-ax225TX-Hackintosh-EFI/files/7319850/USBPort.zip)
> 
> 第二个就是触摸板 触摸板的话，现有的装扮和随机触发的左键珍品，真的就是看心情，我没成功使用过2指或3指代表 （不会是主要的“例子”Xtar）大佬的PS2自组装（雾）
> 
> 如果最后一个大佬出现了，希望能搞搞一下触摸板，谢谢大佬了
> 
> 比心❤️～

大佬我也是相同的问题，你发的这个该怎么使用呢

**Comment by Sword6988** [comment]
> i7 版本 USB 的问题 可以根据个人的实际需要使用 Hackintool 中的 USB 工具自己定制设备的 USB端口 然后直接替换 EFI 中的 ACPI 即可（替换前请注意备份）
> 
> 触摸板的问题 我亲自实测 目前触摸板支持
> 
> * 双指捏合缩放
> * 双指上下滑滚动
> * 双指右边缘左滑展开通知中心
> * 三指上下滑展开调度中心
> * 捏拢拇指及其他三指打开 启动台
> * 张开拇指及其他三指 显示桌面（这个比较难出现，但还是可以使用）
> 
> 为测试通过的仅有
> 
> * 双指在页面间移动 （会识别为前往上一页）
> * 三指左右轻扫（无法识别横向手势）

大佬我的电脑也是i5版本的，但是遇到了跟楼上大哥一样的问题，usb3.0的u盘插在3.0的端口无法识别

**Comment by sve1r** [comment]
> > i7 版本 USB 的问题 可以根据个人的实际需要使用 Hackintool 中的 USB 工具自己定制设备的 USB端口 然后直接替换 EFI 中的 ACPI 即可（替换前请注意备份）
> > 触摸板的问题 我亲自实测 目前触摸板支持
> > 
> > * 双指捏合缩放
> > * 双指上下滑滚动
> > * 双指右边缘左滑展开通知中心
> > * 三指上下滑展开调度中心
> > * 捏拢拇指及其他三指打开 启动台
> > * 张开拇指及其他三指 显示桌面（这个比较难出现，但还是可以使用）
> > 
> > 为测试通过的仅有
> > 
> > * 双指在页面间移动 （会识别为前往上一页）
> > * 三指左右轻扫（无法识别横向手势）
> 
> 大佬我的电脑也是i5版本的，但是遇到了跟楼上大哥一样的问题，usb3.0的u盘插在3.0的端口无法识别

你可以按照上面的方法自己定制试试, 或者等我在下个版本中修复

**Comment by Sword6988** [comment]
我已经搞定了，感谢大佬

**Comment by kimoefox** [comment]
大佬我今天使用的时候确定了一个bug
触摸板是真的没法使用单手指手势
他会把单手默认为双指点按，双膝跪地以求更新

**Comment by kimoefox** [comment]
事实证明：只要时间放的够长，bug就会自动消失
触摸板问题找到原因了，是因为开启了力度检测选项
![截屏2021-11-10 下午11 11 43](https://user-images.githubusercontent.com/47162655/141139275-c342e75a-0021-41d1-9d7f-f7588629b3b9.png)
只要把这个关了，就都正常了
4指触摸的成功概率也会大大加大
（虽然不知道这个让人手掌酸痛的4指手势有什么用）
再次感谢大佬的仔细解答，爱你♥️
