### ISSUE TITLE
更新macOS Monterey

### ISSUE THREAD

**Issue by kimoefox** [sve1r/OMEN-By-HP-15-ax225TX-Hackintosh-EFI#16]
我又来踩坑了
在更新macOS Monterey的时候卡进度条了，（open core还不会开啰嗦模式。。）
不知道大佬有没有兼容Monterey的计划呢？

还有一个问题是
如果usb3..0能正常使用的话，那么理论上说是可以制作一个【macOS to go】的，但是也是卡住了233333

不知道大佬什么时候更新Monterey，挺期待的

**Comment by sve1r** [comment]
emmm ..
会在 大部分 app 都兼容 macOS 12 时才提供升级的计划..
现在大部分插件等都不够稳定...求稳为好

**Comment by kimoefox** [comment]
确实，升级了驱动依然是无法安装，还是得静候大佬的高端操作，谢谢大佬
