### ISSUE TITLE
卡在引导界面

### ISSUE THREAD

**Issue by hellocc321** [sve1r/OMEN-By-HP-15-ax225TX-Hackintosh-EFI#17]
大佬，请教一下，我用黑果小兵的11.6的镜像刻录到U盘之后，把自带的EFI分区的目录替换成你发布的最新的EFI，重启用U盘启动引导安装，苹果进度条界面加载完之后，一直卡在灰色界面，就一个鼠标能动，没其它东西，请问下这是啥原因？我是新手，多多指教一下，电脑是暗影精灵2pro，i7，U盘是3.0

**Comment by sve1r** [comment]
emmm....
我个人不大建议 直接替换镜像里面的 EFI, 
建议使用镜像里的 通用EFI 安装并启动成功之后,再对硬盘中的 EFI 进行替换.
