### ISSUE TITLE
安装12时，找不到硬盘

### ISSUE THREAD

**Issue by poyo96** [sve1r/OMEN-By-HP-15-ax225TX-Hackintosh-EFI#19]
卡在了抹掉硬盘那一步，只显示u盘，不显示硬盘，大佬有遇到过吗？

**Comment by poyo96** [comment]
用clover安装进系统了，换回了oc，发现还是看不到另一块hdd硬盘

**Comment by sve1r** [comment]
如果找不到硬盘的话, 说明 OpenCore 自带的 OpenHfsPlus 还没有适配你的硬盘.
你从最初版本的分支中拷贝一份 HfsPlus.efi 替换掉 OpenhfsPlus 并且修改配置文件再重新试试.
