### ISSUE TITLE
找到了解决最新版本oc启动很慢的问题解决的方法

### ISSUE THREAD

**Issue by innocencenrs** [sve1r/OMEN-By-HP-15-ax225TX-Hackintosh-EFI#23]
仅仅只需要使用IntelBluetoothFirmware.kext，其余的关于蓝牙的kext删除掉即可。因为12版本的蓝牙逻辑发生了改变。同时添加BlueToolFixup.kext即可。并且据个人使用来看，作者似乎没有做usb定制，也可能是我自己做了config的原因，如果有需要我回上传自己定制的usb。

**Comment by sve1r** [comment]
快提PR
我一秒钟都改不下去了

**Comment by innocencenrs** [comment]
[https://share.weiyun.com/fqlqm8jj](url)

**Comment by sve1r** [comment]
已在 latest 分支中修复
