### ISSUE TITLE
Help for Battery Patch

### ISSUE THREAD

**Issue by retrohog** [sve1r/OMEN-By-HP-15-ax225TX-Hackintosh-EFI#24]
HI there I am also having HP OMEN 15 ce0xx and you config worked really good I appreciate your hard work but i want to ask you if you know it is for real my battery stats showing battery service needed and it won't charge just stays at 1% every time.  I am having same specs and also HP OMEN but that looks strange if you could help me for this that would be great .

One more request can you please change language to English in readme because google translate doesn't work so good here on git.
Thanks

**Comment by retrohog** [comment]
One more thing I fixed those all type of wake issues if you need that ACPI patch let me know glad to help you😊

**Comment by sve1r** [comment]
Sure.

1. For the first question, you need to patch the DSDT for your own PC, I hope can these may help
 - [link](https://www.tonymacx86.com/threads/guide-how-to-patch-dsdt-for-working-battery-status.116102/) 
 - [link2 (Chinese)](https://www.jianshu.com/p/ba73943fa57e)
 - [Laptop-DSDT-Patch](https://github.com/RehabMan/Laptop-DSDT-Patch)
 - [video1](https://www.youtube.com/watch?v=PuzbYx9ZQfc)

2. I've already added an English version of the Readme for your understanding

**Comment by retrohog** [comment]
Hey i need your help, i tried all of those guides but didn't got any ending result of working battery patch.
Can you please see my acpi file and guide me or make a battery patch for my config that will be really helpful for me.
I want to mention that i took help from olarila community in case if you think there's any problem with that please let me know.
I tried your efi too it's working fine but in battery stats it's showing service and battery at 1% only.
Uploading my whole folder here please see through it.

ACPI-https://drive.google.com/file/d/14EYCLDOIw_nMv50P3BaCl9fD0ei8Ux6z/view?usp=sharing

Thanks :)

**Comment by sve1r** [comment]
On macOS 13 
Before that, you can try to use  [ECEnabler](https://github.com/1Revenger1/ECEnabler)

Maybe this will help you 



> Hey i need your help, i tried all of those guides but didn't got any ending result of working battery patch.
> 
> Can you please see my acpi file and guide me or make a battery patch for my config that will be really helpful for me.
> 
> I want to mention that i took help from olarila community in case if you think there's any problem with that please let me know.
> 
> I tried your efi too it's working fine but in battery stats it's showing service and battery at 1% only.
> 
> Uploading my whole folder here please see through it.
> 
> 
> 
> ACPI-https://drive.google.com/file/d/14EYCLDOIw_nMv50P3BaCl9fD0ei8Ux6z/view?usp=sharing
> 
> 
> 
> Thanks :)

**Comment by retrohog** [comment]
I tried ecenabler too but i am not getting a battery patch everytime i need to do hard shutdown to check my battery stats or to charge laptop else it will be stuck at charger is connected battery not charging and the percentage will be stuck.
I changed all 16 bits to 8 but still the issue isn't resolved idk what to do now.


> On macOS 13 Before that, you can try to use [ECEnabler](https://github.com/1Revenger1/ECEnabler)
> 
> Maybe this will help you
> 
> > Hey i need your help, i tried all of those guides but didn't got any ending result of working battery patch.
> > Can you please see my acpi file and guide me or make a battery patch for my config that will be really helpful for me.
> > I want to mention that i took help from olarila community in case if you think there's any problem with that please let me know.
> > I tried your efi too it's working fine but in battery stats it's showing service and battery at 1% only.
> > Uploading my whole folder here please see through it.
> > ACPI-https://drive.google.com/file/d/14EYCLDOIw_nMv50P3BaCl9fD0ei8Ux6z/view?usp=sharing
> > Thanks :)

**Comment by sve1r** [comment]
I'm sorry. I didn't see that notifications.
I almost forgot how I fixed that battery patch.
But here are some EFI collections.
Hope that will do a favor.
https://github.com/Baio1977/EFI-Hackintosh-collection

**Comment by sve1r** [comment]
> I tried ecenabler too but i am not getting a battery patch everytime i need to do hard shutdown to check my battery stats or to charge laptop else it will be stuck at charger is connected battery not charging and the percentage will be stuck. I changed all 16 bits to 8 but still the issue isn't resolved idk what to do now.
> 
> > On macOS 13 Before that, you can try to use [ECEnabler](https://github.com/1Revenger1/ECEnabler)
> > Maybe this will help you
> > > Hey i need your help, i tried all of those guides but didn't got any ending result of working battery patch.
> > > Can you please see my acpi file and guide me or make a battery patch for my config that will be really helpful for me.
> > > I want to mention that i took help from olarila community in case if you think there's any problem with that please let me know.
> > > I tried your efi too it's working fine but in battery stats it's showing service and battery at 1% only.
> > > Uploading my whole folder here please see through it.
> > > ACPI-https://drive.google.com/file/d/14EYCLDOIw_nMv50P3BaCl9fD0ei8Ux6z/view?usp=sharing
> > > Thanks :)

I'm sorry. I didn't see that notifications.
I almost forgot how I fixed that battery patch.
But here are some EFI collections.
Hope that will do a favor.
https://github.com/Baio1977/EFI-Hackintosh-collection
