### ISSUE TITLE
kext文件夹里似乎遗漏了IntelBTPatcher.kext

### ISSUE THREAD

**Issue by Firvrill** [sve1r/OMEN-By-HP-15-ax225TX-Hackintosh-EFI#34]
系统版本：Sonoma 14.5
网卡型号：ax 210
直接使用全套EFI可以进入系统，然后发现蓝牙不可用但是Wi-Fi正常工作，这种情况在使用airportitlwm的时候不太常见，经过排查确认是作者的kext列表缺少IntelBTPatcher.kext这一驱动，补全后重启蓝牙正常工作。

ps.希望作者能把config,plist里PI/Generic/SystenProductName项的值修改成Macbook pro 2018或者更新的型号，这样暗影精灵2pro能直接用作者的EFI直接全新安装Sonoma了。

**Comment by sve1r** [comment]
已在 最新提交 Commit 57fd606 中更新
