### ISSUE TITLE
airportitlwm 驱动，无线网卡显示已驱动但搜不到任何信号

### ISSUE THREAD

**Issue by ciallowo** [sve1r/OMEN-By-HP-15-ax225TX-Hackintosh-EFI#4]
如题，整了一天了 :(

@sve1r 不知您那边可以正常使用吗

**Comment by sve1r** [comment]
这边一直都是正常使用的哦 。
看看你的 OpenCore 是什么版本， 启动的时候有没有加载。
我觉得很稳定所以一直用的是 Beta 版本的驱动，你也可以尝试 回到 1.0.0 版本试试看

**Comment by ciallowo** [comment]
> 这边一直都是正常使用的哦 。
> 看看你的 OpenCore 是什么版本， 启动的时候有没有加载。
> 我觉得很稳定所以一直用的是 Beta 版本的驱动，你也可以尝试 回到 1.0.0 版本试试看

我是直接将您的仓库 clone 下来使用的。至于驱动，我在“关于本机”里面查看是完全驱动了的。airportitlwm 各版本我都已经试过一边了，目前在用 1.3.0 Beta。

不知您是否可以将您正在用的 EFI 发给我一份（序列号您可以删去）。

**Comment by ciallowo** [comment]
![截屏2021-01-18 下午8 50 51](https://user-images.githubusercontent.com/76084546/104918162-51c68880-59cf-11eb-8648-1f0bd70639bb.png)
![截屏2021-01-18 下午8 51 34](https://user-images.githubusercontent.com/76084546/104918166-53904c00-59cf-11eb-8eac-4a551c1db9a5.png)

**Comment by sve1r** [comment]
你的系统是 11.1 还是 10.15

**Comment by sve1r** [comment]
你可以尝试在 启动参数中 alcid=28 之前添加 keepsyms=1 再次尝试

**Comment by sve1r** [comment]
我的 EFI 内容和仓库内完全一致。
你可以参考 Config.plist 。可能由于我个人修改了机型 或者去掉了某些参数 引起

[config.zip](https://github.com/sve1r/OMEN-By-HP-15-ax225TX-Hackintosh-EFI/files/5833944/config.zip)

**Comment by ciallowo** [comment]
> 我的 EFI 内容和仓库内完全一致。
> 你可以参考 Config.plist 。可能由于我个人修改了机型 或者去掉了某些参数 引起

非常感谢！

我已经将这个问题提交到了 Itlwm 项目的 issue。我的机型和您一样，系统是 11.1，我会尝试您提供的方案。
