### ISSUE TITLE
博主 请教您一个关于屏幕驱动的问题

### ISSUE THREAD

**Issue by lffscbm** [sve1r/OMEN-By-HP-15-ax225TX-Hackintosh-EFI#6]
我和您的电脑是一样的型号，i5+1050Ti的版本，之前黑苹果基本完美，后来换了个屏幕具体型号为 群创光电N156HCE-GN1  高色域的屏，macos就进不去了，进度条读完就黑屏重启，换回原屏幕又可以正常进，但是新屏幕 用装机通用的efi可以进去系统，显卡提示7M显存，系统重装过问题依旧，现在我是没有一点头绪，向您请教一下 有没有什么思路

**Comment by sve1r** [comment]
1. 7M 显存一般都因为显卡ID注入不正确。你可以尝试使用 装机通用 EFI, 系统安装完成后 **手动使用 Hackintool 生成对应补丁** ，
2. 黑屏无法解决的话 建议添加 启动参数 **-v** 以 log 形式查看对应报错

**Comment by lffscbm** [comment]
谢谢博主回复，我昨天验证了一下，0x591B0000 驱动不了这块屏幕，无限重启，hd630 应该还有个 0x591B0006 但是还没验证，但是我想会不会是 WhateverGreen.kext版本的问题，博主您分享的efi 中的 Lilu.kext  和 WhateverGreen.kext 驱动版本是最新的吗？

**Comment by sve1r** [comment]
两个都是最新的。
你可以尝试用旧版本 或者 用 Github 对应仓库中 RELEASE 的DEBUG 包

**Comment by lffscbm** [comment]
好的 我试试，非常感谢
