### ISSUE TITLE
v0.6.7升级错版本，OC实际是0.5.7（大误！我的锅）

### ISSUE THREAD

**Issue by Evkva** [sve1r/OMEN-By-HP-15-ax225TX-Hackintosh-EFI#7]
Hackintool显示0.5.7
OpenCore Configurator提示旧版本

```
#代码查询
nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version
4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version	REL-057-2020-04-06
```

仓库里文件不对，少了`HfsPlus.efi`，多了`OpenHfsPlus.efi`让我莫名其妙在这里卡了好久……  
Releases中的v0.6.7有`HfsPlus.efi`
旧版本没有下载

![截屏2021-03-30 下午7 50 42](https://user-images.githubusercontent.com/32220583/112984249-3e832680-9191-11eb-8ea5-ca3d35cc4f1c.png)

十分感谢楼主制作了这份EFI，省了不少功夫
不过没想到升级到11.2.2后，居然没法读写NTFS分区，免费软件没适配，收费软件用不起……shell命令`sudo nano /etc/fstab`-`LABEL=下载 none ntfs rw,auto,nobrowse`也不行

碎碎念结束，最后问个问题：请问三码是自动生成的吗？

**Comment by lcdy** [comment]
还有个问题，请问三码是自动生成的吗？

**Comment by sve1r** [comment]
- 首先，升级EFI后如果版本没有变化的话，请先重置一下 NVRam
- Release 中并未跟随仓库更新同时发布，通常会在OpenCore 最新发布版本时更新 Release => 下一步会在GithubAction中启用
- NTFS 读写问题可以等待开源应用的推出，也可以 尝试使用 Tuxera NTFS 的破解版本
- 三码需要自己手动生成，并且自行测试是否支持 iCloud

**Comment by Evkva** [comment]
🤦‍♂️捂脸.jpg 见识浅陋了！

三码有不明白的地方，想要不影响Windows和Windows软件的激活，SystemUUID 是填写从 Windows 还是 macOS 查到的_主板UUID_？

找到两个帖子，分歧在这点
- [Clover 中 SmUUID / CustomUUID 和 OC 中 SystemUUID 填写说明](https://github.com/zty199/HP_Pavilion_15-cb073tx_Hackintosh) 这个说填写Windows上的
- [2.7.3 Config–PlatformInfo–Generic](https://blog.xjn819.com/post/opencore-guide.html) 这个说填写macOS上的

我以为两者会一样，但是分别查询后居然不一致

第二个问题，SystemUUID和硬件UUID不一样是正常的吗？刚开始Google的时候，我以为两者一致。

**Comment by sve1r** [comment]
其实没有必要考虑这么多， 直接使用 OpenCore Configurator 就能自动读取并填写生成 UUID。
你实际需要做的 仅仅是点击当中的生成 Serial Number，然后重启后尝试 登录 iCloud ，
 然后看看能不能与账户绑定就好
