### ISSUE TITLE
OC: Driver AudioDxe.efi at 2 cannot be found! Halting on critical error

### ISSUE THREAD

**Issue by nulldx** [sve1r/OMEN-By-HP-15-ax225TX-Hackintosh-EFI#9]
准备安装时提示
OC: Driver AudioDxe.efi at 0 cannot be found!
Halting on critical error
Driver文件夹里面没有AudioDxe.efi，但是config.plist里面

`		<key>Drivers</key>
		<array>
			<string>OpenRuntime.efi</string>
			<string>OpenCanopy.efi</string>
			<string>OpenHfsPlus.efi</string>
			<string>AudioDxe.efi</string>
		</array>`
请问如何解决

**Comment by sve1r** [comment]
这是原来用来修复音频时候使用的
你可以自己从opencore的官方包中下载这个
或者你也可以 直接将下面的内容删掉
```<string>AudioDxe.efi</string>```
